-- drop tables if exist (ignore errors)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Exam';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Student'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_School';  EXCEPTION WHEN OTHERS THEN NULL; END;
/


CREATE TABLE RoyHadad_School (
    school_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_name VARCHAR2(255),
    settlement VARCHAR2(255),
    area VARCHAR2(255),
    CONSTRAINT chk_area
        CHECK  (area IN ('south' , 'center' , 'north'))
);

CREATE TABLE RoyHadad_Student(
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id NUMBER,
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),

    CONSTRAINT fk_school
        FOREIGN KEY (school_id)
        REFERENCES RoyHadad_School(school_id)
);

CREATE TABLE RoyHadad_Exam(
    exam_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    school_id NUMBER,
    score NUMBER,
    field VARCHAR2(255),
    exam_name VARCHAR2(255),
    exam_date DATE,

    CONSTRAINT fk_exam_student
        FOREIGN KEY (student_id)
        REFERENCES RoyHadad_Student(student_id)
        ,
    CONSTRAINT fk_exam_school
        FOREIGN KEY (school_id)
        REFERENCES RoyHadad_School(school_id)
        ,
    CONSTRAINT chk_score
        CHECK (score BETWEEN 0 AND 100)
);

INSERT INTO RoyHadad_School (school_id , school_name , settlement , area)
 VALUES (1 , 'בית הספר לאומניות' , 'חיפה' , 'north');
INSERT INTO RoyHadad_School (school_id , school_name , settlement , area)
 VALUES (2 , 'בית הספר הריאלי' , 'חיפה' , 'north');
INSERT INTO RoyHadad_School (school_id , school_name , settlement , area)
 VALUES (3 , 'בית הספר לאומניות' , 'תל אביב' , 'center');
INSERT INTO RoyHadad_School (school_id , school_name , settlement , area)
 VALUES (4 , 'בית הספר הריאלי' , 'ראשלצ' , 'center');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (1, 'דפנה', 'בן דוד');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (1, 'יואב', 'כהן');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (2, 'מיכל', 'ברק');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (2, 'אורי', 'לוי');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (3, 'נועה', 'בן שטרית');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (4, 'דניאל', 'אביטל');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (1, 1, 90, 'math', 'מבחן אמצע', DATE '2023-01-15');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (1, 1, 80, 'history', 'מבחן סוף', DATE '2023-06-20');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (2, 1, 60, 'math', 'מבחן אמצע', DATE '2022-02-10');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (3, 2, 70, 'physics', 'מבחן חורף', DATE '1994-12-01');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (3, 2, 85, 'physics', 'מבחן קיץ', DATE '1996-07-01');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (5, 3, 95, 'art', 'מבחן יצירה', DATE '2023-03-01');

--1
--a
SELECT first_name , last_name FROM RoyHadad_Student;

--b
SELECT school_name FROM RoyHadad_School;

--c
SELECT score , field FROM RoyHadad_Exam
WHERE score > 55;

--d
SELECT first_name , last_name FROM RoyHadad_Student
WHERE last_name LIKE 'ב%';

--e
SELECT first_name , last_name FROM RoyHadad_Student
ORDER BY first_name , last_name;

--2

--a
SELECT first_name , last_name
FROM RoyHadad_Student
JOIN RoyHadad_School
ON RoyHadad_School.school_id = RoyHadad_Student.school_id
ORDER BY school_name , first_name , last_name;

--b
SELECT score , exam_date
FROM RoyHadad_Exam
WHERE exam_date >= DATE '1995-01-01';

--c
SELECT first_name , last_name
FROM RoyHadad_Student s1
JOIN RoyHadad_School s2
ON s1.school_id = s2.school_id
WHERE s2.school_name = 'בית הספר הריאלי' AND s2.settlement = 'חיפה';

--d
SELECT school_id , school_name
FROM RoyHadad_School
WHERE area = 'center';

--e
SELECT area, settlement,school_name
FROM RoyHadad_School;

--f
SELECT s.student_id , s.first_name , s.last_name , AVG(e.score) AS average_score
FROM RoyHadad_Student s
JOIN RoyHadad_Exam e
ON s.student_id = e.student_id
WHERE s.first_name = 'דפנה'
GROUP BY s.student_id , s.first_name , s.last_name;

--g
SELECT sc.school_name , s.first_name , s.last_name , e.field , e.score
FROM RoyHadad_Student s
JOIN RoyHadad_School sc
ON s.school_id = sc.school_id
JOIN RoyHadad_Exam e
ON s.student_id = e.student_id AND sc.school_id = e.school_id
WHERE sc.area = 'north';

--3
--a
SELECT sc.school_id , s.student_id , AVG(e.score)
FROM RoyHadad_Student s
JOIN RoyHadad_School sc
ON s.school_id = sc.school_id
JOIN RoyHadad_Exam e
ON e.student_id = s.student_id AND sc.school_id = e.school_id
WHERE sc.school_name = 'בית הספר לאומניות'
GROUP BY 
sc.school_id,
s.student_id;

--b
SELECT sc.school_id , sc.school_name , AVG(e.score)
FROM RoyHadad_School sc
JOIN RoyHadad_Exam e
ON sc.school_id = e.school_id
GROUP BY sc.school_id , sc.school_name;

--c
SELECT sc.school_id , AVG(e.score) 
FROM RoyHadad_School sc
JOIN RoyHadad_Exam e
ON sc.school_id = e.school_id
WHERE sc.school_name = 'בית הספר העירוני א' AND e.field = 'כימיה'
GROUP BY sc.school_id;

--d
SELECT sc.school_id , sc.school_name , AVG(e.score)
FROM RoyHadad_School sc
JOIN RoyHadad_Exam e
ON sc.school_id = e.school_id
WHERE e.field = 'כימיה'
GROUP BY sc.school_id , sc.school_name
ORDER BY AVG(e.score) DESC;

--e
SELECT sc.school_id, sc.school_name, AVG(e.score) AS avg_score
FROM RoyHadad_School sc
LEFT JOIN RoyHadad_Exam e
ON sc.school_id = e.school_id
AND e.field = 'כימיה'
GROUP BY sc.school_id, sc.school_name
ORDER BY avg_score DESC;

--f
SELECT * 
FROM (
    SELECT s.student_id , s.first_name , s.last_name , AVG(e.score)
    FROM RoyHadad_Student s
    JOIN RoyHadad_Exam e
    ON s.student_id = e.student_id
    GROUP BY s.student_id , s.first_name , s.last_name
    ORDER BY AVG(e.score) DESC
    )
FETCH FIRST 1 ROW ONLY;

--g

SELECT *
FROM (
    SELECT s.student_id , s.first_name , s.last_name , AVG(e.score)
    FROM RoyHadad_Student s
    JOIN  RoyHadad_School sc
    ON s.school_id = sc.school_id
    JOIN RoyHadad_Exam e
    ON sc.school_id = e.school_id AND s.student_id = e.student_id
    WHERE e.field = 'מתמטיקה' AND sc.school_name = 'בית הספר העירוני ב'
    GROUP BY s.student_id , s.first_name , s.last_name
    ORDER BY AVG(e.score) DESC
)
FETCH FIRST 1 ROW ONLY;

--h
SELECT school_id ,  school_name , student_id , first_name , last_name , avg_score
FROM (
    SELECT sc.school_id , sc.school_name , s.student_id , s.first_name , s.last_name , AVG(e.score) AS avg_score , RANK()
        OVER(PARTITION BY sc.school_id  ORDER BY AVG(e.score) DESC
    ) AS rnk
    FROM RoyHadad_School sc
    JOIN RoyHadad_Student s
    ON s.school_id = sc.school_id
    JOIN RoyHadad_Exam e
    ON s.student_id = e.student_id AND e.school_id = sc.school_id
    GROUP BY sc.school_id , sc.school_name , s.student_id ,  s.first_name , s.last_name
)
WHERE rnk = 1
ORDER BY avg_score DESC;

--4

--a
INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (1, 'רועי', 'חדד');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (7, 1, 0, 'הכנת סביח', 'מבחן חורף', DATE '1994-12-01');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (7, 1, 0, 'הכנת מטבוחה', 'מבחן קיץ', DATE '1996-07-01');

INSERT INTO RoyHadad_Exam (student_id, school_id, score, field, exam_name, exam_date)
VALUES (7, 1, 100, 'כימיה', 'בניית כור אטומי', DATE '2023-03-01');

--b
DELETE FROM RoyHadad_Exam
WHERE field = 'english'
AND score < 80;

--c
UPDATE RoyHadad_Exam
SET score = 
CASE WHEN score - 3 < 0 THEN 0
ELSE score -3
END
WHERE field = 'מתמטיקה';

--d
UPDATE RoyHadad_Exam
SET score =
CASE WHEN score + 3 > 100 THEN 100
ELSE score + 3
END
WHERE field = 'מתמטיקה';

--end
CREATE OR REPLACE VIEW north_schools AS
SELECT school_id , school_name
FROM RoyHadad_School
WHERE area = 'north';





