--a
ALTER TABLE RoyHadad_School
ADD students_number NUMBER;

--b
CREATE OR REPLACE TRIGGER after_student_insert
AFTER INSERT ON RoyHadad_Student
FOR EACH ROW
BEGIN
    UPDATE RoyHadad_School
    SET students_number = NVL(students_number , 0) + 1
    WHERE school_id = :NEW.school_id;
END;
/

CREATE OR REPLACE TRIGGER after_student_delete
AFTER DELETE ON RoyHadad_Student
FOR EACH ROW
BEGIN
    UPDATE RoyHadad_School
    SET students_number = NVL(students_number , 0) - 1
    WHERE school_id = :OLD.school_id;
END;
/


CREATE OR REPLACE TRIGGER after_student_update
AFTER UPDATE ON RoyHadad_Student
FOR EACH ROW
BEGIN
    IF :OLD.school_id != :NEW.school_id THEN
        UPDATE RoyHadad_School
        SET students_number = NVL(students_number , 0) - 1
        WHERE school_id = :OLD.school_id;
        
        UPDATE RoyHadad_School
        SET students_number = NVL(students_number , 0) + 1
        WHERE school_id = :NEW.school_id;
    END IF;
END;
/
--c
DELETE FROM RoyHadad_Exam;
DELETE FROM RoyHadad_Student;
DELETE FROM RoyHadad_School;

--d
ALTER TABLE RoyHadad_School
MODIFY students_number NUMBER DEFAULT 0;

--e

INSERT INTO RoyHadad_School (school_id , school_name , settlement , area)
 VALUES (1 , 'בית הספר לאומניות' , 'חיפה' , 'north');


INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (1, 'דפנה', 'בן דוד');

INSERT INTO RoyHadad_Student (school_id, first_name, last_name)
VALUES (1, 'יואב', 'כהן');

SELECT * FROM RoyHadad_School;

--2
CREATE TABLE RoyHadad_City(
    city_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR2(255)
);

--a ,b
ALTER TABLE RoyHadad_City
ADD status NUMBER DEFAULT 1;

--c
CREATE OR REPLACE PACKAGE RoyHadad_city_updater AS
    PROCEDURE RoyHadad_update_city;
    END RoyHadad_city_updater; /
    
CREATE OR REPLACE PACKAGE BODY RoyHadad_city_updater AS 
    PROCEDURE RoyHadad_update_city IS
    BEGIN
        UPDATE RoyHadad_City
        SET status = 2
        WHERE status = 1;
    END RoyHadad_update_city;
END RoyHadad_city_updater;
/

--d
BEGIN
    DBMS_SCHEDULER.create_job(
        job_name => 'ROYHADAD_JOB',
        job_type => 'PLSQL_BLOCK',
        job_action => 'BEGIN RoyHadad_city_updater.RoyHadad_update_city; END;',
        start_date => SYSTIMESTAMP,
        repeat_interval => 'FREQ=SECONDLY; INTERVAL=30',
        enabled => TRUE
    );
    END;
    /
