-- drop tables if exist (ignore errors)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Scores';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Exams';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Students'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Schools';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Settlements';  EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE RoyHadad_Settlements(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement  VARCHAR(255) UNIQUE NOT NULL,
    area        VARCHAR(20),
    
    CONSTRAINT chk_area
        CHECK (area IN ('דרום' , 'מרכז' , 'צפון'))
);

CREATE TABLE RoyHadad_Schools (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255),
    settlement_id   NUMBER,
    
    CONSTRAINT fk_settlement
        FOREIGN KEY (settlement_id)
        REFERENCES RoyHadad_Settlements(id)
);



CREATE TABLE RoyHadad_Students(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   NUMBER,
    first_name  VARCHAR2(255),
    last_name   VARCHAR2(255),

    CONSTRAINT fk_school
        FOREIGN KEY (school_id)
        REFERENCES RoyHadad_Schools(id)
);

CREATE TABLE RoyHadad_Exams(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   NUMBER,
    field       VARCHAR2(255),
    name        VARCHAR2(255),
    exam_date   DATE,
    
    CONSTRAINT fk_school_exam
        FOREIGN KEY(school_id)
        REFERENCES RoyHadad_Schools(id)
);

CREATE TABLE RoyHadad_Scores(
    exam_id     NUMBER,
    student_id  NUMBER,
    score       NUMBER,
    
    CONSTRAINT fk_exam_scores
        FOREIGN KEY (exam_id)
        REFERENCES RoyHadad_Exams(id)
        ,
    CONSTRAINT fk_student_scores
        FOREIGN KEY (student_id)
        REFERENCES RoyHadad_Students(id)
        ,
    CONSTRAINT chk_score
        CHECK (score BETWEEN 0 AND 100)
    
);

-- Settlements
INSERT INTO RoyHadad_Settlements (settlement, area) VALUES ('באר שבע', 'דרום');
INSERT INTO RoyHadad_Settlements (settlement, area) VALUES ('תל אביב', 'מרכז');
INSERT INTO RoyHadad_Settlements (settlement, area) VALUES ('חיפה', 'צפון');
INSERT INTO RoyHadad_Settlements (settlement, area) VALUES ('אשדוד', 'דרום');
INSERT INTO RoyHadad_Settlements (settlement, area) VALUES ('ירושלים', 'מרכז');

-- Schools
INSERT INTO RoyHadad_Schools (name, settlement_id) VALUES ('תיכון רמון', 1);
INSERT INTO RoyHadad_Schools (name, settlement_id) VALUES ('גימנסיה הרצליה', 2);
INSERT INTO RoyHadad_Schools (name, settlement_id) VALUES ('בית ספר אלון', 3);
INSERT INTO RoyHadad_Schools (name, settlement_id) VALUES ('מקיף אשדוד', 4);
INSERT INTO RoyHadad_Schools (name, settlement_id) VALUES ('תיכון ירושלים', 5);

-- Students
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (1, 'דניאל', 'כהן');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (1, 'נועה', 'ברק');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (2, 'יובל', 'בן דוד');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (2, 'שירה', 'לוי');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (3, 'איתי', 'ביטון');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (3, 'מאיה', 'שלום');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (4, 'רן', 'בוסקילה');
INSERT INTO RoyHadad_Students (school_id, first_name, last_name) VALUES (5, 'תמר', 'מלכה');

-- Exams
INSERT INTO RoyHadad_Exams (school_id, field, name, exam_date)
VALUES (1, 'מתמטיקה', 'מבחן אמצע', DATE '2025-01-15');

INSERT INTO RoyHadad_Exams (school_id, field, name, exam_date)
VALUES (1, 'אנגלית', 'מבחן סמסטר', DATE '2025-02-10');

INSERT INTO RoyHadad_Exams (school_id, field, name, exam_date)
VALUES (2, 'מדעי המחשב', 'בוחן 1', DATE '2025-01-20');

INSERT INTO RoyHadad_Exams (school_id, field, name, exam_date)
VALUES (3, 'היסטוריה', 'מבחן פתע', DATE '2025-03-01');

INSERT INTO RoyHadad_Exams (school_id, field, name, exam_date)
VALUES (4, 'ספרות', 'מבחן סיום', DATE '2025-02-25');

INSERT INTO RoyHadad_Exams (school_id, field, name, exam_date)
VALUES (5, 'אזרחות', 'בוחן', DATE '2025-01-30');

-- Scores
INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (1, 1, 78);
INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (1, 2, 92);

INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (2, 1, 54);
INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (2, 2, 67);

INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (3, 3, 88);
INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (3, 4, 49);

INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (4, 5, 73);
INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (4, 6, 58);

INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (5, 7, 61);
INSERT INTO RoyHadad_Scores (exam_id, student_id, score) VALUES (6, 8, 45);

COMMIT;

--1
--a
SELECT first_name , last_name 
FROM RoyHadad_Students;

--b
SELECT name 
FROM RoyHadad_Schools;

--c
SELECT s.score , e.field 
FROM RoyHadad_Exams e
JOIN RoyHadad_Scores s
    ON e.id = s.exam_id
WHERE s.score > 55;

--d
SELECT first_name || ' ' || last_name AS full_name
FROM RoyHadad_Students
WHERE last_name LIKE 'ב%';

--e
SELECT first_name , last_name 
FROM RoyHadad_Students
ORDER BY first_name , last_name ASC;