-- drop tables if exist (ignore errors)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Scores';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Exams';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Students'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Schools';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Settlements';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RoyHadad_Areas';  EXCEPTION WHEN OTHERS THEN NULL; END;
/


CREATE TABLE RoyHadad_Areas (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)
);

CREATE TABLE RoyHadad_Settlements (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) UNIQUE NOT NULL,
    area_id     NUMBER,
    
    CONSTRAINT fk_settlements_area_id
        FOREIGN KEY (area_id)
        REFERENCES RoyHadad_Areas(id)
);

CREATE TABLE RoyHadad_Schools (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255),
    settlement_id   NUMBER,
    
    CONSTRAINT fk_schools_settlement_id
        FOREIGN KEY (settlement_id)
        REFERENCES RoyHadad_Settlements(id)
);



CREATE TABLE RoyHadad_Students(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   NUMBER,
    first_name  VARCHAR2(255),
    last_name   VARCHAR2(255),

    CONSTRAINT fk_students_school_id
        FOREIGN KEY (school_id)
        REFERENCES RoyHadad_Schools(id)
);

CREATE TABLE RoyHadad_Exams(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   NUMBER,
    field       VARCHAR2(255),
    name        VARCHAR2(255),
    exam_date   DATE,
    
    CONSTRAINT fk_exams_school_id
        FOREIGN KEY(school_id)
        REFERENCES RoyHadad_Schools(id)
);

CREATE TABLE RoyHadad_Scores(
    exam_id     NUMBER,
    student_id  NUMBER,
    score       NUMBER,
    
    CONSTRAINT fk_scores_exam_id
        FOREIGN KEY (exam_id)
        REFERENCES RoyHadad_Exams(id)
        ,
    CONSTRAINT fk_scores_student_id
        FOREIGN KEY (student_id)
        REFERENCES RoyHadad_Students(id)
        ,
    CONSTRAINT chk_score
        CHECK (score BETWEEN 0 AND 100)
    
);
